export type Config = {
  orderStatuses: [],
  paymentMethods: [],
  sourceSales: [],
  wards: [],
  districts: [],
  cities: [],
  stores: [],
  orderDeliveryTypes: [],
  productPickedErrorTypes: [],
  orderTags: [],
  orderProductItemTags: [],
  fulfillErrorTypes: [],
  employeeRoles: [],
}
