export type Config = {
  orderStatuses: [],
  paymentMethods: [],
  sourceSales: [],
  wards: [],
  districts: [],
  cities: [],
  shippingMethods: [],
  stores: [],
  orderDeliveryTypes: [],
  productPickedErrors: [],
  orderTags: [],
  orderOperationTypes: [],
  fulfillErrorTypes: [],
  employeeRoles: [],
}
