export const ORDER_COUNTER_STATUS: any = {
  ALL: 'Tất cả',
  NEW: 'Mới',
  ASSIGNED: 'Đã phân công',
  CONFIRMED: 'Đã xác nhận',
  STORE_PICKING: 'Đang soạn hàng',
  STORE_PACKED: 'Soạn hàng xong',
  COMPLETED: 'Đã hoàn thành',
  CANCELLED: 'Đã huỷ',
  BOOKED_SHIPPER: "Đã book shipper",
  SHIPPING: "Đang giao hàng"
};

export const ORDER_COUNTER_STATUS_DRIVER: any = {
  ALL: 'Tất cả',
  UPCOMING_DELIVERY: 'Sắp giao',
  ON_TIME_DELIVERY: 'Tới giờ giao',
  OVERDUE_DELIVERY: 'Trễ giờ giao',
};

export const ORDER_COUNTER_STATUS_PRIORITY: any = {
  ALL: 1,
  CONFIRMED: 2,
  STORE_PICKING: 3,
  STORE_PACKED: 4,
  BOOKED_SHIPPER: 5,
  SHIPPING: 6,
  COMPLETED: 7,
  CANCELLED: 8,
};

export const ORDER_COUNTER_STATUS_PRIORITY_DRIVER: any = {
  ALL: 1,
  UPCOMING_DELIVERY: 2,
  ON_TIME_DELIVERY: 3,
  OVERDUE_DELIVERY: 4,
};

export const ORDER_STATUS = {
  ALL: 'ALL',
  NEW: 'NEW',
  ASSIGNED: 'ASSIGNED', 
  CONFIRMED: 'CONFIRMED',
  STORE_PICKING: 'STORE_PICKING',
  STORE_PACKED: 'STORE_PACKED',
  BOOKED_SHIPPER: 'BOOKED_SHIPPER',
  SHIPPING: 'SHIPPING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export enum ORDER_DELIVERY_TYPE {
  CUSTOMER_PICKUP = 'CUSTOMER_PICKUP',
  STORE_DELIVERY = 'STORE_DELIVERY',
  SHIPPER_DELIVERY = 'SHIPPER_DELIVERY',
  APARTMENT_COMPLEX_DELIVERY = 'APARTMENT_COMPLEX_DELIVERY',
  OFFLINE_HOME_DELIVERY = 'OFFLINE_HOME_DELIVERY',
}

export const ORDER_STATUS_ARRAY = Object.values(ORDER_STATUS);

export enum ORDER_TAGS {
  ORDER_CUSTOMER_PICKUP = 'ORDER_CUSTOMER_PICKUP',
  ORDER_STORE_DELIVERY = 'ORDER_STORE_DELIVERY',
  ORDER_SHIPPER_DELIVERY = 'ORDER_SHIPPER_DELIVERY',
  ORDER_FROM_AGENT = 'ORDER_FROM_AGENT',
  ORDER_FROM_CS_CALL_IN = 'ORDER_FROM_CS_CALL_IN',
  ORDER_HAS_COMBO_PRODUCT = 'ORDER_HAS_COMBO_PRODUCT',
  ORDER_HAS_GROUPBUY_PRODUCT = 'ORDER_HAS_GROUPBUY_PRODUCT',
  ORDER_HAS_PREORDER_PRODUCT = 'ORDER_HAS_PREORDER_PRODUCT',
  ORDER_PRINTED_BILLL = 'ORDER_PRINTED_BILLL',
  ORDER_PRINTED_BAG_LABEL = 'ORDER_PRINTED_BAG_LABEL',
}

export const ORDER_STATUS_BADGE_VARIANT = {
  ORDER_CUSTOMER_PICKUP: 'default',
  ORDER_STORE_DELIVERY: 'default',
  ORDER_SHIPPER_DELIVERY: 'default',  
  ORDER_FROM_AGENT: 'purple',
  ORDER_FROM_CS_CALL_IN: 'purple',
  ORDER_HAS_COMBO_PRODUCT: 'danger',
  ORDER_HAS_GROUPBUY_PRODUCT: 'danger',
  ORDER_HAS_PREORDER_PRODUCT: 'danger',
  ORDER_PRINTED_BILLL: 'warning',
  ORDER_PRINTED_BAG_LABEL: 'warning',
};
